name: "Render Markdown"
description: "Render Markdown to HTML"

inputs:

  token:
    description: "GitHub API token"
    required: false

  markdown_file:
    description: "Markdown file to render"
    required: false
    default: "README.md"

outputs:
  html:
    description: "Rendered HTML"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  color: blue
  icon: file-text
